force-app/main/default/objects/Discount_Config__c/Discount_Config__c.object-meta.xml
<CustomObject>
    <description>Used to manage volume discounts for items like batteries</description>
    <label>Discount Config</label>
    <nameField>
        <displayFormat>DC-{000000}</displayFormat>
        <label>Discount Config Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Discount Configs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Discount_Config__c/fields/Finance_Type__c.field-meta.xml
<CustomField>
    <fullName>Finance_Type__c</fullName>
    <description>Type of Financier used for discount to be applied</description>
    <inlineHelpText>Type of Financier used for discount to be applied</inlineHelpText>
    <label>Finance Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cash</fullName>
            </value>
            <value>
                <fullName>Loan</fullName>
            </value>
            <value>
                <fullName>TPO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Discount_Config__c/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>If checked, the product is available for the given discount contig, state and financier. If unchecked, it&apos;s not available.</description>
    <inlineHelpText>If checked, the product is available for the given discount contig, state and financier. If unchecked, it&apos;s not available.</inlineHelpText>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Discount_Config__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <description>Adjusted price of the product for the State / Product / Financier combination</description>
    <inlineHelpText>Adjusted price of the product for the State / Product / Financier combination</inlineHelpText>
    <label>Price</label>
    <precision>12</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Discount_Config__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Product to which the discount will be applied</description>
    <label>Product</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Product must be active</errorMessage>
        <filterItems>
            <field>Product2.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Discount Configs</relationshipLabel>
    <relationshipName>Discount_Configs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Genability_Monthly_Limit__c/Genability_Monthly_Limit__c.object-meta.xml
<CustomObject>
    <label>Genability Monthly Limit</label>
    <nameField>
        <label>Genability Monthly Limit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Genability Monthly Limits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Genability_Monthly_Limit__c/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <formula>Start_Date__c &lt;= TODAY() &amp;&amp; End_Date__c &gt;= TODAY()</formula>
    <label>Is Active?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Genability_Monthly_Limit__c/fields/Standard_Solar_Accounts_Limit__c.field-meta.xml
<CustomField>
    <fullName>Standard_Solar_Accounts_Limit__c</fullName>
    <label>Standard Solar Accounts Limit</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Genability_Monthly_Limit__c/fields/Standard_Storage_Accounts_Limit__c.field-meta.xml
<CustomField>
    <fullName>Standard_Storage_Accounts_Limit__c</fullName>
    <label>Standard Storage Accounts Limit</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Genability_Provider_Account_Id__c/Genability_Provider_Account_Id__c.object-meta.xml
<CustomObject>
    <label>Genability Provider Account Id</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Genability Provider Account Id Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Genability Provider Account Ids</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Genability_Provider_Account_Id__c/fields/Genability_Monthly_Limit__c.field-meta.xml
<CustomField>
    <fullName>Genability_Monthly_Limit__c</fullName>
    <label>Genability Monthly Limit</label>
    <referenceTo>Genability_Monthly_Limit__c</referenceTo>
    <relationshipLabel>Genability Provider Account Ids</relationshipLabel>
    <relationshipName>Genability_Provider_Account_Ids</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Genability_Provider_Account_Id__c/fields/Storage_Account__c.field-meta.xml
<CustomField>
    <fullName>Storage_Account__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Indicates if Genability Storage analysis is included with this account</inlineHelpText>
    <label>Storage Account</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Genability_Provider_Account_Id__c.field-meta.xml
<CustomField>
    <fullName>Genability_Provider_Account_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Genability Provider Account Id</label>
    <referenceTo>Genability_Provider_Account_Id__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Pricing_Cube__c/Pricing_Cube__c.object-meta.xml
<CustomObject>
    <description>captures all necessary data as a reference for payment calculations related to PPAs, leases, and loans</description>
    <label>Pricing Cube</label>
    <nameField>
        <displayFormat>PC-{0000000}</displayFormat>
        <label>Pricing Cube Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pricing Cubes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Pricing_Cube__c/fields/Dealer_Fee__c.field-meta.xml
<CustomField>
    <fullName>Dealer_Fee__c</fullName>
    <label>Dealer Fee</label>
    <precision>14</precision>
    <scale>4</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Pricing_Cube__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <inlineHelpText>The date when the pricing terms end (if applicable).</inlineHelpText>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Pricing_Cube__c/fields/Payment_Factor_1__c.field-meta.xml
<CustomField>
    <fullName>Payment_Factor_1__c</fullName>
    <inlineHelpText>Payment multiplier for the introductory period of the term</inlineHelpText>
    <label>Payment Factor 1</label>
    <precision>9</precision>
    <scale>8</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Pricing_Cube__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <inlineHelpText>The date when the pricing terms start applying.</inlineHelpText>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Pricing_Cube__c/recordTypes/Cash.recordType-meta.xml
<RecordType>
    <fullName>Cash</fullName>
    <active>true</active>
    <description>Consumer funded. $1000 due at signing, remainder at install</description>
    <label>Cash</label>
</RecordType>

force-app/main/default/objects/Pricing_Cube__c/recordTypes/Loan.recordType-meta.xml
<RecordType>
    <fullName>Loan</fullName>
    <active>true</active>
    <description>Financed purchase, homeowner retained</description>
    <label>Loan</label>
</RecordType>

force-app/main/default/objects/Pricing_Cube__c/recordTypes/TPO.recordType-meta.xml
<RecordType>
    <fullName>TPO</fullName>
    <active>true</active>
    <description>3rd Party Owned (PPA &amp; Lease)</description>
    <label>TPO</label>
</RecordType>

force-app/main/default/objects/Product2/fields/AC_to_DC_Efficiency__c.field-meta.xml
<CustomField>
    <fullName>AC_to_DC_Efficiency__c</fullName>
    <defaultValue>96</defaultValue>
    <description>Battery&apos;s AC to DC efficiency</description>
    <inlineHelpText>Battery&apos;s AC to DC efficiency</inlineHelpText>
    <label>AC to DC Efficiency</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Allow_Battery_to_Grid__c.field-meta.xml
<CustomField>
    <fullName>Allow_Battery_to_Grid__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Permit battery to export energy to the grid</description>
    <inlineHelpText>Permit battery to export energy to the grid</inlineHelpText>
    <label>Allow Battery to Grid?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Allow_Grid_to_Battery__c.field-meta.xml
<CustomField>
    <fullName>Allow_Grid_to_Battery__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Allow charging the battery from the grid</description>
    <inlineHelpText>Allow charging the battery from the grid</inlineHelpText>
    <label>Allow Grid to Battery?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Allow_Solar_to_Battery__c.field-meta.xml
<CustomField>
    <fullName>Allow_Solar_to_Battery__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Allow solar generation to charge the battery</description>
    <inlineHelpText>Allow solar generation to charge the battery</inlineHelpText>
    <label>Allow Solar to Battery</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Allow_Solar_to_Grid__c.field-meta.xml
<CustomField>
    <fullName>Allow_Solar_to_Grid__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Permit solar generation to export excess to the grid</description>
    <inlineHelpText>Permit solar generation to export excess to the grid</inlineHelpText>
    <label>Allow Solar to Grid</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/DC_Coupled__c.field-meta.xml
<CustomField>
    <fullName>DC_Coupled__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Is the battery DC Coupled?</description>
    <inlineHelpText>Is the battery DC Coupled?</inlineHelpText>
    <label>DC Coupled?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/DC_to_AC_Efficiency__c.field-meta.xml
<CustomField>
    <fullName>DC_to_AC_Efficiency__c</fullName>
    <defaultValue>96</defaultValue>
    <description>Battery&apos;s DC to AC efficiency</description>
    <inlineHelpText>Battery&apos;s DC to AC efficiency</inlineHelpText>
    <label>DC to AC Efficiency</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Energy_Capacity__c.field-meta.xml
<CustomField>
    <fullName>Energy_Capacity__c</fullName>
    <label>Energy Capacity</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Initial_SoC__c.field-meta.xml
<CustomField>
    <fullName>Initial_SoC__c</fullName>
    <defaultValue>50</defaultValue>
    <description>Battery initial state of charge</description>
    <inlineHelpText>Battery initial state of charge</inlineHelpText>
    <label>Initial SoC</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Max_SoC__c.field-meta.xml
<CustomField>
    <fullName>Max_SoC__c</fullName>
    <defaultValue>100</defaultValue>
    <description>Battery maximum state of charge</description>
    <inlineHelpText>Battery maximum state of charge</inlineHelpText>
    <label>Max SoC</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Min_SoC__c.field-meta.xml
<CustomField>
    <fullName>Min_SoC__c</fullName>
    <defaultValue>10</defaultValue>
    <description>Battery Minimum State of Charge</description>
    <inlineHelpText>Battery Minimum State of Charge</inlineHelpText>
    <label>Min SoC</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Production__c.field-meta.xml
<CustomField>
    <fullName>Production__c</fullName>
    <label>Production</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Rated_Output_Power__c.field-meta.xml
<CustomField>
    <fullName>Rated_Output_Power__c</fullName>
    <label>Rated Output Power</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Solar_DC_to_AC_Efficiency__c.field-meta.xml
<CustomField>
    <fullName>Solar_DC_to_AC_Efficiency__c</fullName>
    <defaultValue>96</defaultValue>
    <description>Efficiency when charging from solar</description>
    <inlineHelpText>Efficiency when charging from solar</inlineHelpText>
    <label>Solar DC to AC Efficiency</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Standard_Price__c.field-meta.xml
<CustomField>
    <fullName>Standard_Price__c</fullName>
    <label>Standard Price</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product2/recordTypes/Adder.recordType-meta.xml
<RecordType>
    <fullName>Adder</fullName>
    <active>true</active>
    <label>Adder</label>
</RecordType>

force-app/main/default/objects/Product2/recordTypes/Battery.recordType-meta.xml
<RecordType>
    <fullName>Battery</fullName>
    <active>true</active>
    <label>Battery</label>
</RecordType>

force-app/main/default/objects/Product2/recordTypes/Panel.recordType-meta.xml
<RecordType>
    <fullName>Panel</fullName>
    <active>true</active>
    <label>Panel</label>
</RecordType>

force-app/main/default/objects/Solar_Estimate_Address__c/Solar_Estimate_Address__c.object-meta.xml
<CustomObject>
    <label>Solar Estimate Address</label>
    <nameField>
        <displayFormat>SEA-{0000000}</displayFormat>
        <label>Solar Estimate Address Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Solar Estimate Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Solar_Estimate_Address__c/fields/Genability_Provider_Account_Id__c.field-meta.xml
<CustomField>
    <fullName>Genability_Provider_Account_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Genability Provider Account Id</label>
    <referenceTo>Genability_Provider_Account_Id__c</referenceTo>
    <relationshipLabel>Solar Estimate Addresses</relationshipLabel>
    <relationshipName>Solar_Estimate_Addresses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/State__c/State__c.object-meta.xml
<CustomObject>
    <description>State related data for defining finance baselines and panels</description>
    <label>State</label>
    <nameField>
        <label>State Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>States</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/State__c/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <formula>IF(
    AND(
        TODAY() &gt;= Start_Date__c,
        OR(
            ISBLANK(End_Date__c),
            TODAY() &lt;= End_Date__c
        )
    ),
    true,
    false
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Is today&apos;s date between the Start and End Date?</inlineHelpText>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/SolarEstimateProcessHelperTest.cls
@IsTest
public with sharing class SolarEstimateProcessHelperTest {
    
    @TestSetup
    static void setup() {
        
        Genability_Monthly_Limit__c genabilityMonthlyLimit = new Genability_Monthly_Limit__c();
        genabilityMonthlyLimit.Name = 'Test';
        genabilityMonthlyLimit.Start_Date__c = Date.today().addDays(-1);
        genabilityMonthlyLimit.End_Date__c = Date.today().addDays(1);
        genabilityMonthlyLimit.Standard_Solar_Accounts_Limit__c = 2;
        genabilityMonthlyLimit.Standard_Storage_Accounts_Limit__c = 1;
        insert genabilityMonthlyLimit;
        
        Genability_Provider_Account_Id__c genabilityProviderAccountId1 = new Genability_Provider_Account_Id__c();
        genabilityProviderAccountId1.Genability_Monthly_Limit__c = genabilityMonthlyLimit.Id;
        genabilityProviderAccountId1.Storage_Account__c = false;
        insert genabilityProviderAccountId1;

        Genability_Provider_Account_Id__c genabilityProviderAccountId2 = new Genability_Provider_Account_Id__c();
        genabilityProviderAccountId2.Genability_Monthly_Limit__c = genabilityMonthlyLimit.Id;
        genabilityProviderAccountId2.Storage_Account__c = true;
        insert genabilityProviderAccountId2;
        
        Product2 panel = new Product2();
        panel.RecordTypeId = SObjectUtil.getRecordTypeIdByName('Product2', 'Panel');
        panel.Name = 'Test Panel';
        panel.Production__c = 100;
        insert panel;
        
        Product2 battery = new Product2();
        battery.RecordTypeId = SObjectUtil.getRecordTypeIdByName('Product2', 'Battery');
        battery.Name = 'Test Battery';
        battery.Family = 'Battery';
        battery.IsActive = true;
        battery.Standard_Price__c = 100;
        battery.Rated_Output_Power__c = '1';
        battery.Energy_Capacity__c = '1';
        battery.Min_SoC__c = 1;
        battery.Max_SoC__c = 1;
        battery.Initial_SoC__c = 1;
        battery.DC_Coupled__c = true;
        battery.AC_to_DC_Efficiency__c = 1;
        battery.DC_to_AC_Efficiency__c = 1;
        battery.Solar_DC_to_AC_Efficiency__c = 1;
        battery.Allow_Battery_to_Grid__c = true;
        battery.Allow_Grid_to_Battery__c = true;
        battery.Allow_Solar_to_Grid__c = true;
        battery.Allow_Solar_to_Battery__c = true;
        insert battery;
        
        Product2 solarTaxFilingService = new Product2();
        solarTaxFilingService.RecordTypeId = SObjectUtil.getRecordTypeIdByName('Product2', 'Adder');
        solarTaxFilingService.Name = 'Solar Tax Filing Service';
        solarTaxFilingService.Family = 'Administrative';
        solarTaxFilingService.IsActive = true;
        insert solarTaxFilingService;
        
        Product2 safeStreetsBasicsPackage = new Product2();
        safeStreetsBasicsPackage.RecordTypeId = SObjectUtil.getRecordTypeIdByName('Product2', 'Adder');
        safeStreetsBasicsPackage.Name = 'SafeStreets / Google Smart Home: Basics Package';
        safeStreetsBasicsPackage.Family = 'Smart Home';
        safeStreetsBasicsPackage.IsActive = true;
        insert safeStreetsBasicsPackage;
        
        Pricing_Cube__c cashPreferred = new Pricing_Cube__c();
        cashPreferred.RecordTypeId = SObjectUtil.getRecordTypeIdByName('Pricing_Cube__c', 'Cash');
        cashPreferred.Dealer_Fee__c = 1.5;
        insert cashPreferred;
        
        Pricing_Cube__c loanPreferred = new Pricing_Cube__c();
        loanPreferred.RecordTypeId = SObjectUtil.getRecordTypeIdByName('Pricing_Cube__c', 'Loan');
        loanPreferred.Dealer_Fee__c = 1.5;
        loanPreferred.Payment_Factor_1__c = 0.1;
        insert loanPreferred;
        
        Discount_Config__c discountConfig1 = new Discount_Config__c();
        discountConfig1.Product__c = battery.Id;
        discountConfig1.Is_Active__c = true;
        discountConfig1.Finance_Type__c = 'Cash;Loan;TPO';
        discountConfig1.Min_Quantity__c = 1;
        discountConfig1.Max_Quantity__c = 3;
        discountConfig1.Price__c = 100;
        insert discountConfig1;
        
        Discount_Config__c discountConfig2 = new Discount_Config__c();
        discountConfig2.Product__c = solarTaxFilingService.Id;
        discountConfig2.Is_Active__c = true;
        discountConfig2.Min_Quantity__c = 1;
        discountConfig2.Price__c = 100;
        insert discountConfig2;
        
        Discount_Config__c discountConfig3 = new Discount_Config__c();
        discountConfig3.Product__c = safeStreetsBasicsPackage.Id;
        discountConfig3.Is_Active__c = true;
        discountConfig3.Min_Quantity__c = 1;
        discountConfig3.Price__c = 100;
        insert discountConfig3;
        
        State__c state = new State__c();
        state.Cash_Panel__c = panel.Id;
        state.Cash_Battery__c = battery.Id;
        state.Cash_Preferred__c = cashPreferred.Id;
        state.Loan_Panel__c = panel.Id;
        state.Loan_Battery__c = battery.Id;
        state.Loan_Preferred__c = loanPreferred.Id;
        state.Loan_Competitor__c = loanPreferred.Id;
        state.TPO_Panel__c = panel.Id;
        state.TPO_Battery__c = battery.Id;
        state.Name = 'CA';
        state.Start_Date__c = Date.today().addDays(-10);
        state.Auto_Recommend_Battery__c = true;
        state.Cash_Base_PPW__c = 0.1;
        state.Cash_Margin__c = 0.1;
        state.Competitor_Cash_PPW__c = 0.1;
        state.Loan_Base_PPW__c = 0.1;
        state.Loan_Margin__c = 0.1;
        state.TPO_Base_PPW__c = 0.1;
        state.TPO_Margin__c = 0.1;
        insert state;
        
        Lead ld = new Lead();
        ld.FirstName = 'FirstName';
        ld.LastName = 'LastName';
        ld.Company = 'Test Company';
        ld.Phone = '12345';
        ld.Email = 'FirstName.LastName@gmail.com';
        ld.Street = 'Test';
        ld.City = 'Test';
        ld.State = 'CA';
        ld.PostalCode = '12345';
        ld.Country = 'US';
        ld.Status = 'Open';
        ld.LeadSource = 'Web';
        ld.Utility_Company__c = 'Test';
        ld.Lse_Id__c = '12345';
        ld.Average_Monthly_Bill__c = 100;
        insert ld;
    }
    
    @IsTest
    static void solarEstimateProcessTest() {
        
        Lead ld = [SELECT Id 
                   FROM Lead 
                   LIMIT 1];
        
        Test.startTest();
        
        Map<String, String> defaultValues = SolarEstimateProcessHelper.getDefaultValuesForSolarEstimate();
        
        Solar_Estimate_Address__c solarEstimateAddress = SolarEstimateProcessHelper.upsertSolarEstimateAddress(ld.Id);
        
        solarEstimateAddress.Safe_Streets__c = 'Basics Package';
        solarEstimateAddress.Solar_Tax_Filing_Service__c = true;
        solarEstimateAddress.Initiate_Solar_Estimate_Process__c = true;
        
        update solarEstimateAddress;
        
        Test.stopTest();
    }
}